name = "theomanager-signaling"
type = "javascript"

account_id = "2f77a877cb3dbf335a3ffd7e49c98627"
workers_dev = true

[durable_objects]
bindings = [
  { name = "SIGNALING_DO", class_name = "SignalingDO" }
]
