name = "theomanager-signaling"
main = "src/index.js"
compatibility_date = "2025-02-26"

[[durable_objects.bindings]]
name = "SIGNALING_DO"
class_name = "SignalingDO"

[env.staging]
name = "theomanager-signaling-staging"
